# Generated by Django 5.1.6 on 2025-02-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDRP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_details',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
